# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 575eff8c652ee77e8e729af9bf4b845affe51c25d674450d9f75de6c44ce739bac38c222543ab0ecf3a948f25c9b1d4a6454c0fbb670a7abee331ecf43f2c7bb

test:
  secret_key_base: e99fb7243d78aa36f8990138267980b6ecb1839607c3262f96c6f986ce5fd2b3494f055e98003d483ff6c9720337990c11ecc4ee42408b813482e7e634631dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
